const lib=require('./TestModule')
console.log(lib.Colour.Random())
console.log(lib.Date.Random())
console.log(lib.City.Random(10))
console.log(lib.Company.Random(10,2,3,true))
console.log(lib.Address.Random(10))
console.log(lib.Mobile.Random(true))
console.log(lib.Password.Random(8,8))
console.log(lib.Pincode.Random(true))
console.log(lib.Telephone.Random(true))
console.log(lib.Currency.Random(true))
console.log(lib.Name.Random(8,1,8,true))
console.log(lib.Email.Random(1))
console.log(lib.Domain.Random(1))
console.log(lib.Description.Random(500,10))
console.log(lib.Designation.Random(10,1,10,true))
console.log(lib.Gender.Validate("Male"))